# Generated by Django 3.1.7 on 2021-04-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
            ],
        ),
    ]
