# Generated by Django 3.1.7 on 2021-04-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210416_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='carb',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='protien',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.CharField(max_length=100),
        ),
    ]
