# Generated by Django 3.1.7 on 2021-04-17 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20210417_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
