# Generated by Django 3.1.7 on 2021-04-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20210418_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='sugar',
        ),
    ]
