# Generated by Django 3.1.7 on 2021-04-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_remove_food_sugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='protien',
            new_name='protein',
        ),
    ]
