# Generated by Django 3.1.7 on 2021-04-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=120)),
                ('foodDish', models.CharField(max_length=300)),
                ('protien', models.CharField(max_length=4)),
            ],
        ),
    ]
